### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by ghost** [stwagnr/tpm2simulator#2]
Hello,
I'm cannot install the tmp2simulator.
The problem is when doing 

> cmake -G "Unix Makefiles" ../cmake -DCMAKE_BUILD_TYPE=Debug -DSPEC_VERSION=116` the output is:

```
SyntaxError: Missing parentheses in call to 'print'
CMake Error at CMakeLists.txt:39 (MESSAGE):
  ERROR: Please update settings.py in the directory 'script'

-- Configuring incomplete, errors occurred!
See also "/home/davider/Scrivania/davide/tpm2simulator/build/CMakeFiles/CMakeOutput.log".
```

Any help??

**Comment by stwagnr** [comment]
Hi! Can you verify step 2 in **Extracting the source code**, especially the second part of

> Edit configuration settings in the file `tpm2simulator/scripts/settings.py` and change `SET = False` to `SET = True` when finished

**Comment by ghost** [comment]
I can't understand, what i have to modify before changing SET = True?

**Comment by stwagnr** [comment]
You _can_ change, for example, the MANUFACTURER, VENDOR_STRING_1, and FIRMWARE_V1.
You _must_ change `SET = False` to `SET = True`.
